# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: s4u/maven-settings-action@v2.3.0
      with:
        servers: |
            [{
                "id": "github",
                "username": "$GITHUB_ACTOR",
                "password": "${{ github.token }}"
            }]
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml

    - name: Build with Maven
      run: mvn -B package --file selenium-utils/pom.xml -s /home/runner/.m2/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
        
    - name: Create release
      uses: actions/create-release@v1 
      env:
        GITHUB_TOKEN: "${{ github.token }}"
      with:
        tag_name: "latest"
        release_name: "latest"
        prerelease: false
        files: |
          target/*.jar

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy --file selenium-utils/pom.xml -s /home/runner/.m2/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
